export const PERSONAL_SETTINGS = 'PERSONAL_SETTINGS'
export const PERSONAL_SETTINGS_THEME = 'PERSONAL_SETTINGS_THEME'
export const PREVIEW_THEME = 'PREVIEW_THEME'
export const RESET_PERSONAL_SETTINGS = 'RESET_PERSONAL_SETTINGS'


export const LOG_DATA = 'LOG_DATA';
export const USER_INFO = 'USER_INFO';

//PRIVATE CABINET TYPES
export const GET_FOLDERS = 'GET_FOLDERS';
export const CHOOSE_FOLDER = 'CHOOSE_FOLDER';
export const CHOOSE_FILES = 'CHOOSE_FILES';
export const LOAD_FILES = 'LOAD_FILES';
export const SET_FILES_PATH = 'SET_FILES_PATH';
export const LOAD_FILES_ALL = 'LOAD_FILES_ALL';
export const CHOOSE_ALL_FILES = 'CHOOSE_ALL_FILES';
export const FILE_DELETE = 'FILE_DELETE';
export const ADD_RECENT_FILES = 'ADD_RECENT_FILES';
export const ADD_RECENT_FOLDERS = 'ADD_RECENT_FOLDERS';
export const CHOOSE_RECENT_FILES = 'CHOOSE_RECENT_FILES';
export const CUSTOMIZE_FILE = 'CUSTOMIZE_FILE';
export const SET_SIZE = 'SET_SIZE';
export const SET_WORKELEMENTSVIEW = 'SET_WORKELEMENTSVIEW';
export const SEARCH = 'SEARCH';
export const CHOOSE_SHARED_FILES = 'CHOOSE_SHARED_FILES';
export const CHOOSE_ARCHIVE_FILES = 'CHOOSE_ARCHIVE_FILES';
export const SORT_FILES = 'SORT_FILES';
export const SET_FILTER_COLOR = 'SET_FILTER_COLOR';
export const SET_FILTER_EMOJI = 'SET_FILTER_EMOJI';
export const SET_FILTER_FIGURE = 'SET_FILTER_FIGURE';
export const SET_REVERSE_CRITERION = 'SET_REVERSE_CRITERION';
export const NULLIFY_FILTERS = 'NULLIFY_FILTERS';
export const SET_DRAGGED = 'SET_DRAGGED';
export const LOAD_FILES_NEXT = 'LOAD_FILES_NEXT';
export const CHOOSE_FILES_NEXT = 'CHOOSE_FILES_NEXT';
export const SET_NEXT_FILES_TO_PREVIOUS = 'SET_NEXT_FILES_TO_PREVIOUS';

export const CONTACT_LIST = 'CONTACT_LIST';
export const COMPANY_CONTACT_LIST = 'COMPANY_CONTACT_LIST';

//PROGRAMS TYPES
export const GET_PROGRAM_FOLDERS = 'GET_PROGRAM_FOLDERS'
export const GET_PROGRAMS = 'GET_PROGRAMS'
export const GET_RECENT_PROGRAMS = 'GET_RECENT_PROGRAMS'
export const GET_TOP_LIST_PROGRAMS = 'GET_TOP_LIST_PROGRAMS'
export const GET_CATEGORIES = 'GET_CATEGORIES'

//SAFES
export const GET_SAFES = 'GET_SAFES'
export const LOAD_SAFE_FILELIST = 'LOAD_SAFE_FILELIST'
export const CHOOSE_SAFE_FILELIST = 'CHOOSE_SAFE_FILELIST'
export const AUTHORIZED_SAFE = 'AUTHORIZED_SAFE'
export const CHOOSE_SAFE_FILES = 'CHOOSE_ALL_FILES';
export const CUSTOMIZE_SAFE_FILE = 'CUSTOMIZE_SAFE_FILE';
export const SAFE_FILE_DELETE = 'SAFE_FILE_DELETE';
export const CODE_TEL = 'CODE_TEL';

//DEVICES
export const GET_DEVICES = 'GET_DEVICES'
export const SET_SELECTED_DEVICE = 'SET_SELECTED_DEVICE'
export const SET_SELECTED_USER = 'SET_SELECTED_USER'
export const GET_CONNECTED_CONTACTS = 'GET_CONNECTED_CONTACTS'

//PROJECT
export const GET_PROJECTS = 'GET_PROJECTS'
export const GET_PROJECT_FOLDER = 'GET_PROJECT_FOLDER'
export const LOAD_PROJECT_FILES = 'LOAD_PROJECT_FILES'
export const SET_CHOSEN_FOLDER = 'SET_CHOSEN_FOLDER'
export const SET_CHOSEN_PROJECT = 'SET_CHOSEN_PROJECT'


//JOURNAL
export const GET_JOURNAL_FOLDERS = 'GET_JOURNAL_FOLDERS'

//CALENDAR DATE
export const SET_CALENDAR_DATE = 'SET_CALENDAR_DATE'
export const SET_CALENDAR_EVENTS = 'SET_CALENDAR_EVENTS'

//GUEST MODE
export const CHOOSE_GUEST_SHARED_FILES = 'CHOOSE_GUEST_SHARED_FILES'

//COMPANY
export const COMPANY_DOCUMENTS = 'COMPANY_DOCUMENTS'

//PAINT
export const SET_PAINT = 'SET_PAINT'
