export const SET_ROUTE = 'SET_ROUTE';


export const LOG_DATA = 'LOG_DATA';
export const USER_INFO = 'USER_INFO';

//PRIVATE CABINET TYPES
export const GET_FOLDERS = 'GET_FOLDERS';
export const CHOOSE_FOLDER = 'CHOOSE_FOLDER';
export const CHOOSE_FILES = 'CHOOSE_FILES';
export const CHOOSE_ALL_FILES = 'CHOOSE_ALL_FILES';
export const FILE_DELETE = 'FILE_DELETE';
export const ADD_RECENT_FILES = 'ADD_RECENT_FILES';
export const ADD_RECENT_FOLDERS = 'ADD_RECENT_FOLDERS';
export const CHOOSE_RECENT_FILES = 'CHOOSE_RECENT_FILES';
export const CUSTOMIZE_FILE = 'CUSTOMIZE_FILE';
export const SET_SIZE = 'SET_SIZE';

export const CONTACT_LIST = 'CONTACT_LIST';

//PROGRAMS TYPES
export const GET_PROGRAM_FOLDERS = 'GET_PROGRAM_FOLDERS'
export const GET_PROGRAMS = 'GET_PROGRAMS'
export const GET_RECENT_PROGRAMS = 'GET_RECENT_PROGRAMS'
export const GET_TOP_LIST_PROGRAMS = 'GET_TOP_LIST_PROGRAMS'
export const GET_CATEGORIES = 'GET_CATEGORIES'

//SAFES
export const GET_SAFES = 'GET_SAFES'

//DEVICES
export const GET_DEVICES = 'GET_DEVICES'
export const GET_CONNECTED_CONTACTS = 'GET_CONNECTED_CONTACTS'

